AIRPORTS = [
    # iata, city, full name, aliases (comma-separated)
    ("ATL", "Atlanta",         "Hartsfield-Jackson Atlanta International",  "atlanta,atl"),
    ("LAX", "Los Angeles",     "Los Angeles International",                  "los angeles,la,lax,los angeles international"),
    ("ORD", "Chicago",         "O'Hare International",                       "chicago,ohare,o'hare,chi"),
    ("DFW", "Dallas",          "Dallas/Fort Worth International",            "dallas,fort worth,dfw,dallas fort worth"),
    ("DEN", "Denver",          "Denver International",                       "denver,den"),
    ("JFK", "New York",        "John F. Kennedy International",              "new york,nyc,jfk,new york city,ny"),
    ("SFO", "San Francisco",   "San Francisco International",                "san francisco,sf,sfo"),
    ("SEA", "Seattle",         "Seattle-Tacoma International",               "seattle,sea,seattle tacoma,seatac"),
    ("LAS", "Las Vegas",       "Harry Reid International",                   "las vegas,vegas,lv,las"),
    ("MCO", "Orlando",         "Orlando International",                      "orlando,mco"),
    ("MIA", "Miami",           "Miami International",                        "miami,mia"),
    ("CLT", "Charlotte",       "Charlotte Douglas International",            "charlotte,clt"),
    ("PHX", "Phoenix",         "Phoenix Sky Harbor International",           "phoenix,phx,sky harbor"),
    ("EWR", "Newark",          "Newark Liberty International",               "newark,ewr,newark liberty"),
    ("IAH", "Houston",         "George Bush Intercontinental",               "houston,iah,bush intercontinental"),
    ("BOS", "Boston",          "Boston Logan International",                 "boston,bos,logan"),
    ("MSP", "Minneapolis",     "Minneapolis-Saint Paul International",       "minneapolis,saint paul,msp,minneapolis saint paul"),
    ("DTW", "Detroit",         "Detroit Metropolitan Wayne County",          "detroit,dtw,metro detroit"),
    ("FLL", "Fort Lauderdale", "Fort Lauderdale-Hollywood International",    "fort lauderdale,fll,fort lauderdale hollywood"),
    ("PHL", "Philadelphia",    "Philadelphia International",                 "philadelphia,phl,philly"),
    ("LGA", "New York",        "LaGuardia Airport",                          "laguardia,lga,la guardia"),
    ("BWI", "Baltimore",       "Baltimore/Washington International",         "baltimore,bwi,bwi thurgood marshall"),
    ("DCA", "Washington",      "Ronald Reagan Washington National",          "washington,dca,reagan,national airport"),
    ("IAD", "Washington",      "Washington Dulles International",            "dulles,iad,washington dulles"),
    ("MDW", "Chicago",         "Chicago Midway International",               "midway,mdw,chicago midway"),
    ("SLC", "Salt Lake City",  "Salt Lake City International",               "salt lake city,slc,salt lake"),
    ("PDX", "Portland",        "Portland International",                     "portland,pdx"),
    ("SAN", "San Diego",       "San Diego International",                    "san diego,san"),
    ("HNL", "Honolulu",        "Daniel K. Inouye International",             "honolulu,hawaii,hnl,oahu"),
    ("AUS", "Austin",          "Austin-Bergstrom International",             "austin,aus"),
    ("STL", "St. Louis",       "St. Louis Lambert International",            "st louis,saint louis,stl"),
    ("MCI", "Kansas City",     "Kansas City International",                  "kansas city,mci"),
    ("RDU", "Raleigh",         "Raleigh-Durham International",               "raleigh,durham,rdu,raleigh durham"),
    ("MSY", "New Orleans",     "Louis Armstrong New Orleans International",  "new orleans,msy,louis armstrong"),
    ("SMF", "Sacramento",      "Sacramento International",                   "sacramento,smf"),
    ("SJC", "San Jose",        "Norman Y. Mineta San Jose International",    "san jose,sjc,mineta,san jose mineta"),
    ("OAK", "Oakland",         "Oakland International",                      "oakland,oak"),
    ("BNA", "Nashville",       "Nashville International",                    "nashville,bna"),
    ("CLE", "Cleveland",       "Cleveland Hopkins International",            "cleveland,cle"),
    ("PIT", "Pittsburgh",      "Pittsburgh International",                   "pittsburgh,pit"),
    ("MEM", "Memphis",         "Memphis International",                      "memphis,mem"),
    ("CVG", "Cincinnati",      "Cincinnati/Northern Kentucky International", "cincinnati,cvg"),
    ("IND", "Indianapolis",    "Indianapolis International",                 "indianapolis,ind"),
    ("CMH", "Columbus",        "John Glenn Columbus International",          "columbus,cmh"),
    ("LHR", "London",          "Heathrow Airport",                           "london,heathrow,lhr"),
    ("CDG", "Paris",           "Charles de Gaulle Airport",                  "paris,cdg,charles de gaulle"),
    ("NRT", "Tokyo",           "Narita International Airport",               "tokyo,nrt,narita"),
    ("YVR", "Vancouver",       "Vancouver International Airport",            "vancouver,yvr,vancouver bc"),
    ("YYZ", "Toronto",         "Toronto Pearson International",              "toronto,yyz,pearson"),
    ("AAL", "Aalborg",         "Aalborg Airport",                            "aalborg,aal"),
]
